version: '3.8'

services:
  tweetyproject-web-server:
    image: ghcr.io/odzhychko/tweetyproject/tweetyproject-web-server:causal-reasoner-snapshot@sha256:425444d8988f9c4c0533383a405fec9eeca3df52bbf7dbab7344f98899c181ed
    ports:
      - "8080:8080"

  aig-causal-knowledge-base-editor:
    image: ghcr.io/aig-hagen/aig-causal-knowledge-base-editor:latest
    ports:
      - "3000:80"
    environment:
      - TWEETY_API_URL=http://localhost:8080
    depends_on:
      - tweetyproject-web-server