name: Publish
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-image:
    runs-on: ubuntu-24.04

    # Permissions required for publishing Docker image.
    # See https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
    # And permissions required for creating releases.
    # See https://github.com/softprops/action-gh-release
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Use Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24.13.0

      - name: Install dependencies
        run: npm install-clean

      - name: Build
        run: npm run build
        env:
          VITE_EDITOR_VERSION: ${{ github.ref_name }}
          VITE_EDITOR_COMMIT: ${{ github.sha }}

        # The URL is set to '' (empty string) because the frontend
        # will be served by the backend server.
      - name: Set backend URL
        run: sed -i "s|\$TWEETY_API_URL||g" ./dist/index.html

      - name: Build docs
        run: npm run docs:build

      - name: Bundle web server with frontend
        id: bundle_with_server
        run: |
          ./bundle-with-server.sh
          VERSION="${GITHUB_REF_NAME#v}"
          SERVER_ARTIFACT="${RUNNER_TEMP}/org.tweetyproject.web-with-causal-knowledge-base-editor-${VERSION}.jar"
          mv "${RUNNER_TEMP}/org.tweetyproject.web-with-causal-knowledge-base-editor.jar" $SERVER_ARTIFACT
          echo "server_artifact=$SERVER_ARTIFACT" >> $GITHUB_OUTPUT

      - name: Publish web server with frontend
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          files: ${{ steps.bundle_with_server.outputs.server_artifact }}

      # The Docker setup follows
      # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
      # Attestation is disabled because it is only available for public repositories.
      # See https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
